version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine3.10

    working_directory: /app

    steps:
      - checkout
      - run: python3 -c 'import sys; f = open("/usr/local/lib/python3.7/site-packages/_manylinux.py", "w"); f.write("manylinux1_compatible = True"); f.close()'
      - run: python -m pip install -r requirements.txt
      - run: flake8 --max-line-length=240 bot.py